services:
  feed-server:
    image: nginx:alpine
    volumes:
      - ./runtime/feed:/feed:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    restart: unless-stopped

  builder:
    build: ./builder
    volumes:
      - ./runtime:/runtime
      - ./runtime/feed:/feed
      - cache-sdk:/opt/sdk
      - cache-repos:/opt/repos
    environment:
      - TERM=xterm
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID
    restart: unless-stopped

volumes:
  cache-sdk:
  cache-repos:
